export const homePath = '/';
export const matchesPath = '/matches';
export const matchIdKey = 'matchId';
export const matchPath = `${matchesPath}/:${matchIdKey}`;
export const playPath = '/play';
export const coursePickerPath = playPath + '/courses';
export const holePickerPath = playPath + '/holes';
export const loginPath = '/login';
export const logoutPath = '/logout';
