[[table]]
	name = "accounts"

[[table]]
	name = "locations"

[[table]]
	name = "courses"

[[table]]
	name = "holes"

[[table]]
	name = "matches"

[[table]]
	name = "match_participants"

[[table]]
	name = "match_strokes"

[[query]]
	name = "GetAllLocations"
	return_type = "[]*Location"
	body = '''
	SELECT * FROM locations;
	'''
