// Code generated by sqlc. DO NOT EDIT.
// source: location.sql

package db

import (
	"context"
	"database/sql"
)

const createHole = `-- name: CreateHole :one
INSERT INTO holes (
  number, name,  par
) VALUES (
  $1, $2, $3
)
RETURNING id, number, name, par
`

type CreateHoleParams struct {
	Number int16          `json:"number"`
	Name   sql.NullString `json:"name"`
	Par    int16          `json:"par"`
}

func (q *Queries) CreateHole(ctx context.Context, arg CreateHoleParams) (Hole, error) {
	row := q.db.QueryRow(ctx, createHole, arg.Number, arg.Name, arg.Par)
	var i Hole
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.Par,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  name
) VALUES (
  $1
)
RETURNING id, name
`

func (q *Queries) CreateLocation(ctx context.Context, name string) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation, name)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
