// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Hole struct {
	ID     int64          `json:"id"`
	Number int16          `json:"number"`
	Name   sql.NullString `json:"name"`
	Par    int16          `json:"par"`
}

type Location struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
