// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateHole(ctx context.Context, arg CreateHoleParams) (Hole, error)
	CreateLocation(ctx context.Context, name string) (Location, error)
}

var _ Querier = (*Queries)(nil)
