// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hole struct {
	ID     string  `json:"id"`
	Number int     `json:"number"`
	Name   *string `json:"name"`
	Par    int     `json:"par"`
}

type HoleInputs struct {
	Number int     `json:"number"`
	Name   *string `json:"name"`
	Par    int     `json:"par"`
}

type Location struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Holes []*Hole `json:"holes"`
}
