// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hole struct {
	ID     int64   `json:"id"`
	Number int32   `json:"number"`
	Name   *string `json:"name"`
	Par    int32   `json:"par"`
}

type Location struct {
	ID    int64   `json:"id"`
	Name  string  `json:"name"`
	Holes []*Hole `json:"holes"`
}
