// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CourseInputs struct {
	Name  string        `json:"name"`
	Holes []*HoleInputs `json:"holes"`
}

type HoleInputs struct {
	CourseOrder int32 `json:"course_order"`
	Par         int32 `json:"par"`
}
